name: ConTeXt Action
description: A GitHub Action for ConTeXt
author: Luigi Russo
inputs:
  main-tex:
    description: Path to main file
    required: true
    default: main.tex
  working-directory:
    description: The working directory for ConTeXt
    required: false
  args:
    description: Extra arguments to be passed to context
    required: false
    default: ""
  force-command:
    description: Raw command to be executed
    required: false
    default: ""
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.main-tex}}
    - ${{ inputs.working-directory}}
    - ${{ inputs.args }}
    - ${{ inputs.force-command }}
branding:
  icon: file-text
  color: blue
