name: ConTeXt Action
description: A GitHub Action for ConTeXt
author: Luigi Russo
inputs:
  main-tex:
    description: Path to main file
    required: true
    default: main.tex
  working-directory:
    description: The working directory for ConTeXt
    required: false
  args:
    description: Extra arguments to be passed to context
    required: false
    default: "--batchmode"
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.main-tex}}
    - ${{ inputs.working-directory}}
    - ${{ inputs.args }}
branding:
  icon: file-text
  color: blue
