name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test ConTeXt Github Action
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v2
      - name: Compile basic ConTeXt file
        uses: ./
        with:
          main-tex: test.tex
          working-directory: test/
      - name: Compile ConTeXt file with custom args
        uses: ./
        with:
          main-tex: test.tex
          working-directory: test/
          args: "--result=custom-test"
      - name: Compile ConTeXt file with arbitrary command
        uses: ./
        with:
          force-command: "context main --result=foo"
